using System;

namespace POCC {

	public enum SceneType {
		MAIN_MENU, GAME_OVER, END_LEVEL_SCENE, TUTORIAL_1, TUTORIAL_2, HUB_1,
		LOGOS, HUB_2, BEARLANA, PATHOS_1, PATHOS_2, HUB_3, ETHOS_1, ETHOS_2,
		HUB_4, END_OF_YEAR
	}	
}
